### Variables
@baseUrl = http://localhost:8000
@jwtToken = {{loginRequest.response.body.*}}

### Login
# @name loginRequest
POST {{baseUrl}}/api/auth/login
Content-Type: application/json

{
    "email": "analista@seplag.rj.gov.br",
    "password": "orcamento@2026"
}

### GET /graficos
GET {{baseUrl}}/api/graficos
Authorization: Bearer {{jwtToken}}
Accept: application/json