### Variables
@baseUrl = http://localhost:8000
@jwtToken = {{loginRequest.response.body.*}}

### Login
# @name loginRequest
POST {{baseUrl}}/api/auth/login
Content-Type: application/json

{
    "email": "analista@seplag.rj.gov.br",
    "password": "orcamento@2026"
}

### GET /orgaos
GET {{baseUrl}}/api/orgaos
    ?busca=secretaria
    &ativo=true
    &per_page=3
    &page=2
Authorization: Bearer {{jwtToken}}