services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      DB_HOST: mysql
      DB_DATABASE: seplag
      DB_USERNAME: root
      DB_PASSWORD: root
    ports:
      - 8000:8000
    volumes:
      - ./backend:/app/backend
    depends_on:
      - mysql
    networks:
      - app

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    tty: true
    ports:
      - 3000:3000
    volumes:
      - ./frontend:/app/frontend
      - /app/frontend/node_modules
    depends_on:
      - backend
    networks:
      - app

  mysql:
    image: mysql:8.4
    environment:
      MYSQL_DATABASE: 'seplag'
      # MYSQL_USER: 'root'
      # MYSQL_PASSWORD: 'root'
      MYSQL_ROOT_PASSWORD: 'root'
    volumes:
      - dbdata:/var/lib/mysql/
    networks:
      - app

networks:
  app:
    driver: bridge

volumes:
  dbdata: